name: Audit

on:
  schedule:
    - cron: "0 9 * * 2"

jobs:

  frontend-audit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - uses: actions/checkout@v3

      - name: Initialise dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Audit the dependencies
        run: npm audit

  backend-audit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Initialise dependencies
        run: |
          pip install pdm
          pdm install

      - name: Audit the dependencies
        run: pdm run audit
